using System;
using System.Drawing;
using System.Windows.Forms;
/// <summary>
///   Author(s):       Joe Zachary
///                    Jim de St. Germain - Refactor/Documentation for ASP Core
///   Course:          CS 3500
///   Date:            2011 Sept   - Initial Grid Code
///                    2020 Spring - Refactor for ASP Core
///   
///   Partial:
/// 
///     The code for this class is divided into two files using C#'s partial ability.
///     The other half is in the SpreadsheetGridWidget.cs file.  This code was
///     (somewhat) automatically generated by the WYSIWYG design editor.  It should not
///     be directly modified.  Personalizations should be done in the other half of the partial.
/// 
///   Contents:
///   
///     See SpreadsheetGridWidget.cs for more information.
/// 
/// </summary>
namespace SpreadsheetGrid_Framework
{
    partial class SpreadsheetGridWidget
    {
        /// <summary> 
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary> 
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Component Designer generated code

        /// <summary> 
        /// Required method for Designer support - do not modify 
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.hScroll = new System.Windows.Forms.HScrollBar();
            this.vScroll = new System.Windows.Forms.VScrollBar();
            this.Input_textBox = new System.Windows.Forms.TextBox();
            this.drawingPanel = new SpreadsheetGrid_Framework.DrawingPanel();
            this.SuspendLayout();
            // 
            // hScroll
            // 
            this.hScroll.Location = new System.Drawing.Point(0, 483);
            this.hScroll.Name = "hScroll";
            this.hScroll.Size = new System.Drawing.Size(483, 17);
            this.hScroll.TabIndex = 0;
            // 
            // vScroll
            // 
            this.vScroll.Location = new System.Drawing.Point(483, 0);
            this.vScroll.Name = "vScroll";
            this.vScroll.Size = new System.Drawing.Size(17, 483);
            this.vScroll.TabIndex = 1;
            // 
            // Input_textBox
            // 
            this.Input_textBox.Location = new System.Drawing.Point(196, 170);
            this.Input_textBox.Name = "Input_textBox";
            this.Input_textBox.Size = new System.Drawing.Size(87, 20);
            this.Input_textBox.TabIndex = 4;
            this.Input_textBox.TextChanged += new System.EventHandler(this.running);
            this.Input_textBox.Visible = false;
            this.Input_textBox.KeyDown += new System.Windows.Forms.KeyEventHandler(this.Input_textbox_KeyDown);

            // 
            // drawingPanel
            // 
            this.drawingPanel.Location = new System.Drawing.Point(0, 0);
            this.drawingPanel.Margin = new System.Windows.Forms.Padding(4);
            this.drawingPanel.Name = "drawingPanel";
            this.drawingPanel.Size = new System.Drawing.Size(483, 483);
            this.drawingPanel.TabIndex = 3;
            // 
            // SpreadsheetGridWidget
            // 
            this.BackColor = System.Drawing.SystemColors.MenuHighlight;
            this.Controls.Add(this.Input_textBox);
            this.Controls.Add(this.drawingPanel);
            this.Controls.Add(this.vScroll);
            this.Controls.Add(this.hScroll);
            this.Name = "SpreadsheetGridWidget";
            this.Size = new System.Drawing.Size(500, 500);
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion

        private HScrollBar hScroll;
        private VScrollBar vScroll;
        private DrawingPanel drawingPanel;
        private TextBox Input_textBox;
    }
}